name: concurrency
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 
jobs:
  build:
    runs-on: ubuntu-latest #Linux OS.
    steps:
      - name: step1
        run: sleep 20