name: parellel
on: [push] 
job1: #these should be unique
  build:
    runs-on: ubuntu-latest #Linux OS.
    steps:
      - name: step1
        run: echo "Hi, I am from JOB1"

job2:
  build:
    runs-on: ubuntu-latest #Linux OS.
    steps:
      - name: step1
        run: echo "Hi, I am from JOB2"

job3:
  build:
    runs-on: ubuntu-latest #Linux OS.
    steps:
      - name: step1
        run: echo "Hi, I am from JOB3"